max_width = 100
hard_tabs = false
tab_spaces = 4
imports_indent = "Block"
imports_layout = "Vertical"
imports_granularity = "Module"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true
